version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-rc-management

  gamesshop.gateway:
    image: ${DOCKER_REGISTRY-}gamesshopgateway 
    container_name: games-shop.gateway
    build:
      context: .
      dockerfile: GamesShop.Gateway/Dockerfile
    environment:
        - identityServerConnectionString=http://games-shop.identity-server:5000

  gamesshop.identityserver:
    image: ${DOCKER_REGISTRY-}gamesshopidentityserver
    container_name: games-shop.identity-server
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: GamesShop.IdentityServer/Dockerfile

