version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-rc-management

  gamesshop.gateway:
    image: ${DOCKER_REGISTRY-}gamesshopgateway 
    container_name: games-shop.gateway
    ports:
      - "7000:80"
    build:
      context: .
      dockerfile: GamesShop.Gateway/Dockerfile
    environment:
        - identityServerConnectionString=http://games-shop.identity-server:5000

  gamesshop.identityserver:
    image: ${DOCKER_REGISTRY-}gamesshopidentityserver
    container_name: games-shop.identity-server
    ports:
      - "5000:80"
    environment:
      IDENTITY_SERVER_DATABASE_CONNECTION_STRING: "Server=postgres-database;Database=identityDb;Username=postgres;Password=root"
      ASP_NET_IDENTITY_DATABASE_CONNECTION_STRING: "Server=postgres-database;Database=identityUserDb;Username=postgres;Password=root"
    build:
      context: .
      dockerfile: GamesShop.IdentityServer/Dockerfile

  gamesshop.catalog.api:
    image: ${DOCKER_REGISTRY-}gamesshopcatalogapi
    container_name: games-shop.catalog-api
    # development
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: GamesShop.Catalog.API/Dockerfile
    environment:
        - mongoDBConnectionString=mongo-database
        - mongoDataBaseName=games-shop
  
  mongo-database:
    image: mongo
    container_name: mongo-database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongo-database
    depends_on:
      - mongo-database

  postgres:
    container_name: postgres-database
    image: postgres:latest
    user: root
    environment:
      POSTGRES_DB: "identityDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: postgres-admin
    image: dpage/pgadmin4:latest
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  mongodb-data:
  pgadmin-data:
  postgres-data:
    driver: local